### ISSUE TITLE
Cannot run Bonsai.Miniscope: Unhandled exception on line 59 of UCLAMiniscope.cs

### ISSUE THREAD

**Issue by galenlynch** [jonnew/Bonsai.Miniscope#5]
The line is:
`using (var capture = Capture.CreateCameraCapture(Index))`

The error is: 
```
An exception of type 'System.TypeInitializationException' occurred in OpenCV.Net.dll but was not handled in user code

Additional information: The type initializer for 'OpenCV.Net.Native.NativeMethods' threw an exception.
```

**Comment by jonnew** [comment]
This was taken care of by linking against the OpenCV.NET dll on your local bonsai installation rather than the one that was (erroneously) included in this repo.
